import Layout from "components/layout";
import Head from "next/head";
import { ReactElement } from "react";

export default function Home() {
	return (
		<div>
			<Head>
				<title>Lucas Consejo | Développeur web</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
				<meta name="theme-color" content="rgb(26, 8, 66)"></meta>
			</Head>
		</div>
	);
}

Home.getLayout = function getLayout(page: ReactElement) {
	return <Layout>{page}</Layout>;
};
