const data = [
    {
        id: "kubernetes",
        text: "Kubernetes",
        src: "/lucasconsejo/logo/kubernetes.webp",
        url: "https://kubernetes.io/fr/",
        className:"lg:w-9 lg:h-9"
    },
    {
        id: "docker",
        text: "Docker",
        src: "/lucasconsejo/logo/docker.webp",
        url: "https://www.docker.com/",
        className:"lg:w-9 lg:h-9"
    },
    {
        id: "docker-compose",
        text: "Docker compose",
        src: "/lucasconsejo/logo/docker-compose.webp",
        url: "https://docs.docker.com/compose/",
        className: "lg:w-9 lg:h-9",
    },
    {
        id: "grafana",
        text: "Grafana",
        src: "/lucasconsejo/logo/grafana.webp",
        url: "https://grafana.com/",
        className: "lg:w-9 lg:h-9",
    },
    {
        id: "kibana",
        text: "Kibana",
        src: "/lucasconsejo/logo/kibana.webp",
        url: "https://www.elastic.co/fr/kibana/",
        className: "lg:w-9 lg:h-9",
    },
    {
        id: "jenkins",
        text: "Jenkins",
        src: "/lucasconsejo/logo/jenkins.webp",
        url: "https://www.jenkins.io/",
        className: "lg:w-9 lg:h-9"
    },
    {
        id: "gitlab-cicd",
        text: "Pipeline Gitlab",
        src: "/lucasconsejo/logo/gitlab.webp",
        url: "https://docs.gitlab.com/ee/ci/",
        className: "lg:w-9 lg:h-9"
    },
    {
        id: "git",
        text: "Git",
        src: "/lucasconsejo/logo/git.webp",
        url: "https://git-scm.com/",
        className: "lg:w-9 lg:h-9",
    },
    {
        id: "sonar",
        text: "Sonarqube",
        src: "/lucasconsejo/logo/sonar.webp",
        url: "https://www.sonarqube.org/",
        className: "lg:w-9 lg:h-9",
    },
    {
        id: "jest",
        text: "Jest",
        src: "/lucasconsejo/logo/jest.webp",
        url: "https://jestjs.io/fr/",
        className: "lg:w-8 lg:h-8",
    },
    {
        id: "ansible",
        text: "Ansible",
        src: "/lucasconsejo/logo/ansible.webp",
        url: "https://docs.ansible.com/ansible/latest/index.html",
        className: "lg:w-9 lg:h-9",
    },
    {
        id: "vagrant",
        text: "Vagrant",
        src: "/lucasconsejo/logo/vagrant.webp",
        url: "https://www.vagrantup.com/",
        className: "lg:w-9 lg:h-9",
    },
    {
        id: "azure",
        text: "Microsoft Azure",
        src: "/lucasconsejo/logo/azure.webp",
        url: "https://azure.microsoft.com/fr-fr/",
        className: "lg:w-9 lg:h-9",
    },
    {
        id: "dotnet",
        text: "Microsoft .NET",
        src: "/lucasconsejo/logo/dotnet.webp",
        url: "https://dotnet.microsoft.com/en-us/",
        className: "lg:w-9 lg:h-9",
    },
    {
        id: "laravel",
        text: "Laravel",
        src: "/lucasconsejo/logo/laravel.webp",
        url: "https://laravel.com/",
        className: "lg:w-9 lg:h-9",
    },
    {
        id: "symfony",
        text: "Symfony",
        src: "/lucasconsejo/logo/symfony.webp",
        url: "https://symfony.com/",
        className: "lg:w-9 lg:h-9",
    },
    {
        id: "mongo",
        text: "MongoDB",
        src: "/lucasconsejo/logo/mongo.webp",
        url: "https://www.mongodb.com/",
        className: "lg:w-9 lg:h-9",
    },
    {
        id: "firebase",
        text: "Firebase",
        src: "/lucasconsejo/logo/firebase.webp",
        url: "https://firebase.google.com/",
        className: "lg:w-9 lg:h-9",
    },
    {
        id: "couchbase",
        text: "Couchbase",
        src: "/lucasconsejo/logo/couchbase.webp",
        url: "https://www.couchbase.com/fr",
        className: "lg:w-9 lg:h-9",
    },
    {
        id: "sqlserver",
        text: "SQL Server",
        src: "/lucasconsejo/logo/sqlserver.webp",
        url: "https://www.microsoft.com/fr-fr/sql-server/",
        className: "lg:w-9 lg:h-9",
    },
    {
        id: "postgresql",
        text: "PostgreSQL",
        src: "/lucasconsejo/logo/postgresql.webp",
        url: "https://www.postgresql.org/",
        className: "lg:w-9 lg:h-9",
    },
    {
        id: "mysql",
        text: "MySQL",
        src: "/lucasconsejo/logo/mysql.webp",
        url: "https://www.mysql.com/fr/",
        className: "lg:w-9 lg:h-9",
    },
    {
        id: "kafka",
        text: "Apache Kafka",
        src: "/lucasconsejo/logo/kafka.webp",
        url: "https://kafka.apache.org/",
        className: "lg:w-9 lg:h-9",
    },
    {
        id: "solr",
        text: "Apache Solr",
        src: "/lucasconsejo/logo/solr.webp",
        url: "https://solr.apache.org/",
        className: "lg:w-9 lg:h-9",
    },
    {
        id: "figma",
        text: "Figma",
        src: "/lucasconsejo/logo/figma.webp",
        url: "https://www.figma.com/",
        className: "lg:w-12 lg:h-12",
    },
    {
        id: "jira",
        text: "Jira",
        src: "/lucasconsejo/logo/jira.webp",
        url: "https://www.atlassian.com/fr/software/jira",
        className: "lg:w-9 lg:h-9",
    },
    {
        id: "raspberry",
        text: "Raspberry Pi",
        src: "/lucasconsejo/logo/raspberry.webp",
        url: "https://www.raspberrypi.com/",
        className: "lg:w-10 lg:h-10",
    },
    {
        id: "arduino",
        text: "Arduino",
        src: "/lucasconsejo/logo/arduino.webp",
        url: "https://www.arduino.cc/",
        className: "lg:w-10 lg:h-10",
    },
];

export default data;
