import { ProjectType } from "./types";

const projects: Array<ProjectType> = [
    {
        img: "/lucasconsejo/projects/nostetourtiere.webp",
        icon: "/lucasconsejo/logo/nostetourtiere.webp",
        title: "Noste Tourtière",
        url: "https://www.nostetourtiere.com",
        isStudentProject: false,
        technos: [
            "Next JS",
            "Typescript",
            "Tailwind CSS",
            "Gitlab CI/CD",
            "Express JS",
            "MongoDB",
        ],
        isApp: false,
    },
    {
        img: "/lucasconsejo/projects/dashboard.webp",
        icon: "/lucasconsejo/logo/dashboard.webp",
        title: "Dashboard - Noste Tourtière",
        url: "",
        isStudentProject: true,
        technos: [
            "React JS",
            "Typescript",
            "Tailwind CSS",
            "Gitlab CI/CD",
            "Express JS",
            "MongoDB",
        ],
        isApp: false,
    },
    {
        img: "/lucasconsejo/projects/notes.webp",
        icon: "/lucasconsejo/logo/notes.webp",
        title: "Notes",
        url: "https://play.google.com/store/apps/details?id=com.lucasconsejo.notes",
        isStudentProject: false,
        technos: [
            "React Native",
            "SQLite",
        ],
        isApp: true,
    },
    {
        img: "/lucasconsejo/projects/reverse-eats.webp",
        icon: "/lucasconsejo/logo/reverse-eats.webp",
        title: "Reverse Eats",
        url: "",
        isStudentProject: true,
        technos: [
            "React Native",
            "Typescript",
            "Gitlab CI/CD",
            "NodeJS",
            "Firebase",
        ],
        isApp: false,
    },
    {
        img: "/lucasconsejo/projects/conore.webp",
        icon: "/lucasconsejo/logo/conore.svg",
        title: "Conore",
        url: "",
        isStudentProject: true,
        technos: [
            "React Native",
            "Symfony",
            "Stripe",
            "MySQL",
            "Gitlab CI/CD",
            "Kubernetes",
            "Grafana",
        ],
        isApp: false,
    },
    {
        img: "/lucasconsejo/projects/react-svg-color.webp",
        icon: "/lucasconsejo/logo/npm.svg",
        title: "react-svg-color",
        url: "https://www.npmjs.com/package/react-svg-color",
        isStudentProject: false,
        technos: ["React JS", "Gitlab CI/CD"],
        isApp: false,
    },
    {
        img: "/lucasconsejo/projects/lucasconsejo.webp",
        icon: "/lucasconsejo/logo/favicon.webp",
        title: "lucasconsejo",
        url: "https://lucasconsejo.fr",
        isStudentProject: false,
        technos: ["Next JS", "Typescript", "Gitlab CI/CD"],
        isApp: false,
    },
    {
        img: "/lucasconsejo/projects/hmp.webp",
        icon: "/lucasconsejo/logo/hmp.webp",
        title: "Heal me please",
        url: "",
        isStudentProject: true,
        technos: [
            "Next JS",
            "Typescript",
            "Nest JS",
            "PostgreSQL",
            "Gitlab CI/CD",
            "Kubernetes",
            "Grafana",
        ],
        isApp: false,
    },
    {
        img: "/lucasconsejo/projects/wimm.webp",
        icon: "/lucasconsejo/logo/wimm.webp",
        title: "Where is my money",
        url: "",
        isStudentProject: true,
        technos: ["React JS", "Typescript", "Laravel", "MySQL", "Gitlab CI/CD"],
        isApp: false,
    },
    {
        img: "/lucasconsejo/projects/reactly.webp",
        icon: "/lucasconsejo/logo/reactly.webp",
        title: "Reactly",
        url: "",
        isStudentProject: true,
        technos: [
            "React JS",
            "Typescript",
            "Express JS",
            "Firebase",
            "MongoDB",
            "Gitlab CI/CD",
        ],
        isApp: false,
    },
    {
        img: "/lucasconsejo/projects/abc.webp",
        icon: "/lucasconsejo/logo/react.webp",
        title: "Entreprise ABC",
        url: "",
        isStudentProject: true,
        technos: ["React JS", "Tailwind CSS", ".NET", "MongoDB", "Jenkins"],
        isApp: false,
    },
    {
        img: "/lucasconsejo/projects/player.webp",
        icon: "/lucasconsejo/logo/react.webp",
        title: "Music player",
        url: "https://music-player-copperdev.vercel.app/",
        isStudentProject: false,
        technos: ["React JS"],
        isApp: false,
    },
    {
        img: "/lucasconsejo/projects/calculatrice.webp",
        icon: "/lucasconsejo/logo/react.webp",
        title: "Calculatrice",
        url: "https://calculator-copperdev.vercel.app/",
        isStudentProject: false,
        technos: ["React JS"],
        isApp: false,
    },
    {
        img: "/lucasconsejo/projects/atoute.webp",
        icon: "/lucasconsejo/logo/react.webp",
        title: "Atoute",
        url: "",
        isStudentProject: true,
        technos: [
            "React JS",
            "Typescript",
            "Symfony",
            "MySQL",
            "Gitlab CI/CD",
            "Elasticsearch",
            "Kibana",
        ],
        isApp: false,
    },
    {
        img: "/lucasconsejo/projects/sospr.webp",
        icon: "/lucasconsejo/logo/sospr.webp",
        title: "SOSPR",
        url: "",
        isStudentProject: true,
        technos: ["Laravel", "Tailwind CSS", "Active Directory", "MySQL"],
        isApp: false,
    },
    {
        img: "/lucasconsejo/projects/sylab.webp",
        icon: "/lucasconsejo/logo/sylab.webp",
        title: "Sylab",
        url: "",
        isStudentProject: true,
        technos: ["Symfony", "Bootstrap", "MySQL"],
        isApp: false,
    },
];

export default projects;
